source 'https://github.com/CocoaPods/Specs.git'

target 'FMMosaicLayout', :exclusive => true do
  pod "FMMosaicLayout", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "FMMosaicLayout", :path => "../"
end
